STAGE_Z_BOUNDS = 0.025
STAGE_STABLE_TIMEOUT = 1

X_STAGE_NAME = 'base_x_stage_joint'
Y_STAGE_NAME = 'x_y_stage_joint'
Z_STAGE_NAME = 'y_z_stage_joint'

STAGE_JOINT_NAMES = [X_STAGE_NAME, Y_STAGE_NAME, Z_STAGE_NAME]

MARKER_WIDTH_METERS = 200e-6
MARKER_HEIGHT_METERS = MARKER_WIDTH_METERS / 4

MARKER_HORIZ_GAP = 0.01
MARKER_VERT_GAP = 0.01
N_MARKER_ROWS = 5
N_MARKER_COLS = 5